<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- NuGet metadata -->
        <PackageId>$(AssemblyName)</PackageId>
        <Authors>l4mberjack</Authors>
        <Description>Memory Storage — Фролов Дмитрий ИП-22-3</Description>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>Storage;InMemoryStorage;ListStorage</PackageTags>
        <Product>$(AssemblyName)</Product>

        <!-- Сборка nuget при билдe -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>1.0.6</Version>

        <!-- Очень важно -->
        <IncludeBuildOutput>true</IncludeBuildOutput>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    </ItemGroup>


    <!-- Проекты, которые должны попасть внутрь пакета -->
    <ItemGroup>
        <ProjectReference Include="..\Entities\Entities.csproj" />
        <ProjectReference Include="..\Repository.Contracts\Repository.Contracts.csproj" />
        <ProjectReference Include="..\Services.Contracts\Services.Contracts.csproj" />
    </ItemGroup>


    <!-- README + ICON -->
    <ItemGroup>
        <None Update="README.md" Pack="true" PackagePath="\" />
        <None Update="icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
